repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        files: (?i)\.(json|js|jsx|ts|tsx)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.12.1
    hooks:
      - id: eslint
        files: (?i)\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - 'eslint@7.12.1'
          - 'eslint-config-prettier@6.15.0'
