name: "Finite state automata"
description: "Implementing finite state automata in Python. I also wrote a [blog post](https://ljvmiranda921.github.io/notebook/2022/10/07/finite-state-automata/) about it."
